fix(dpkg): Add missing short option -R
scop/bash-completion pull request #1249
Opened 2024-09-24 02:08 UTC by elboulangero

Completion for '--raw-extract' is already supported, however the equivalent short option '-R' was missing. Now fixed.

Cf. dpkg-deb help message:

```
dpkg-deb --help
[...]
  -R|--raw-extract <deb> <directory>
[...]
```

2024-09-24 03:54 UTC, akinomyoga requested changes
Thanks for your contribution. The value of `noargopts` on line 75 should also be updated.

2024-09-24 04:47 UTC, elboulangero commented
Indeed, thanks for your review! I updated the PR.

2024-09-24 07:17 UTC, akinomyoga approved these changes

2024-09-25 19:37 UTC, yedayak approved these changes

2024-09-25 19:38 UTC, merged