fix issue #436 Color-Bug if ip is an alias
scop/bash-completion pull request #439
Opened 2020-08-10 16:18 UTC by johannes-schmatz

change all
```
ip link show
```
to something like this
```
(ip -c=never link show || ip link show)
```

2020-08-15 18:57 UTC, scop commented on bash_completion
> +            LC_ALL=C ifconfig -a || (ip -c=never link show || ip link show)
Please remove the parenthesis from everywhere, they're not needed, and actually start an unnecessary subshell.

2020-08-31 19:22 UTC, scop commented
completions/ip still needs to be addressed...

2020-09-05 15:26 UTC, johannes-schmatz commented
AFAIK completions/ip does call _available_interfaces, so there's no ip invocation

2020-09-06 09:44 UTC, scop commented
It calls at least `$1 help`, `$1 r`, and `$1 netns` -- `$1` there is the `ip` command being invoked.

2020-09-06 18:35 UTC, johannes-schmatz commented
Thank you! I didn't find them by searching 'ip'

2020-09-10 18:12 UTC, scop requested changes

2020-09-10 18:12 UTC, scop commented on completions/ip
> +                COMPREPLY=($(compgen -W "help $($1 -c=never help 2>&1 || $1 help 2>&1 | command sed -e \
This is not correct; both `$1` calls need to be wrapped in `{ ... }` like `{ $1 -c=never help || $1 help; } 2>&1 || command ...`

2020-09-10 18:12 UTC, scop commented on completions/ip
> +                        COMPREPLY=($(compgen -W "$($1 -c=never r || $1 r | command sed -ne \
Same as above.

2020-09-10 18:12 UTC, scop commented on completions/ip
> +                            $($1 -c=never r || $1 r | cut -d ' ' -f 1)" -- "$cur"))
Same as above.

2020-09-10 18:12 UTC, scop commented on completions/ip
> +                        COMPREPLY=($(compgen -W "$($1 -c=never netns list || $1 netns list)" -- "$cur"))
The first one needs a `2>&1` here.

2020-09-12 15:57 UTC, merged

2020-09-12 16:00 UTC, scop commented
Applied with some output redirection fixes to completions/ip.