Clarify language and grammar
scop/bash-completion pull request #715
Opened 2022-03-07 20:04 UTC by mavaddat

2022-03-08 17:13 UTC, scop requested changes

2022-03-08 18:14 UTC, mavaddat commented on README.md
> +(above works if you have *only* bash >= 4.2 installed; see further if not)
Yes, sounds good. Clear.

2022-03-13 13:15 UTC, scop commented on README.md
> +(above works if you have *only* bash >= 4.2 installed; see further if not)
Can I ask you to update the PR with the discussed changes? Thanks!

2022-03-15 22:07 UTC, mavaddat commented on README.md
> +(above works if you have *only* bash >= 4.2 installed; see further if not)
Yes. Doing now.

2022-05-05 18:50 UTC, merged

2022-05-05 18:51 UTC, scop commented
Addressed open conversations and merged as 6f1bbda3c66814befa8025d49363b4070ef20008.